version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "" # Senha vazia para o usuário root, consistente com a configuração original
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Permite senha vazia para o root no MySQL 8
      MYSQL_DATABASE: sistema_estudo
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql # Volume para persistência dos dados do banco
    ports:
      - "3306:3306" # Expõe a porta 3306 para acesso externo, se necessário
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: