const MATERIAIS_FALLBACK = [
  { titulo: 'Matemática Básica - Khan Academy', categoria: 'Matemática', url: 'https://pt.khanacademy.org/math/cc-sixth-grade-math', descricao: 'Fundamentos de matemática: frações, decimais, porcentagem e mais' },
  { titulo: 'Álgebra Completa - Khan Academy', categoria: 'Matemática', url: 'https://pt.khanacademy.org/math/algebra', descricao: 'Equações, inequações, funções e expressões algébricas' },
  { titulo: 'Geometria Plana - Brasil Escola', categoria: 'Matemática', url: 'https://brasilescola.uol.com.br/matematica/geometria-plana.htm', descricao: 'Áreas, perímetros, triângulos, círculos e polígonos' },
  { titulo: 'Trigonometria - Stoodi', categoria: 'Matemática', url: 'https://www.stoodi.com.br/blog/matematica/trigonometria/', descricao: 'Seno, cosseno, tangente e relações trigonométricas' },
  { titulo: 'Estatística e Probabilidade - Khan Academy', categoria: 'Matemática', url: 'https://pt.khanacademy.org/math/statistics-probability', descricao: 'Média, mediana, moda, desvio padrão e probabilidade' },
  { titulo: 'Funções do 1º e 2º Grau - Descomplica', categoria: 'Matemática', url: 'https://descomplica.com.br/artigo/funcoes/', descricao: 'Funções lineares, quadráticas e suas representações gráficas' },
  { titulo: 'Gramática Portuguesa Completa - Brasil Escola', categoria: 'Português', url: 'https://brasilescola.uol.com.br/gramatica', descricao: 'Classes gramaticais, sintaxe, morfologia e ortografia' },
  { titulo: 'Interpretação de Texto - Stoodi', categoria: 'Português', url: 'https://www.stoodi.com.br/blog/portugues/interpretacao-de-texto/', descricao: 'Técnicas para interpretar textos dissertativos e literários' },
  { titulo: 'Redação ENEM - Descomplica', categoria: 'Português', url: 'https://descomplica.com.br/artigo/redacao-enem/', descricao: 'Estrutura da redação, competências e temas recorrentes' },
  { titulo: 'Literatura Brasileira - Brasil Escola', categoria: 'Português', url: 'https://brasilescola.uol.com.br/literatura', descricao: 'Modernismo, Romantismo, Realismo e principais autores' },
  { titulo: 'História do Brasil Colônia - Brasil Escola', categoria: 'História', url: 'https://brasilescola.uol.com.br/historiab/brasil-colonia.htm', descricao: 'Descobrimento, capitanias hereditárias e ciclos econômicos' },
  { titulo: 'Segunda Guerra Mundial - Khan Academy', categoria: 'História', url: 'https://pt.khanacademy.org/humanities/world-history/euro-hist/wwii-causes/a/the-causes-of-world-war-ii', descricao: 'Causas, desenvolvimento e consequências da 2ª Guerra' },
  { titulo: 'Cinemática - Brasil Escola', categoria: 'Física', url: 'https://brasilescola.uol.com.br/fisica/cinematica.htm', descricao: 'MRU, MRUV, queda livre e lançamento de projéteis' },
  { titulo: 'Dinâmica - Leis de Newton - Stoodi', categoria: 'Física', url: 'https://www.stoodi.com.br/blog/fisica/leis-de-newton/', descricao: 'As três leis de Newton com exemplos e exercícios' },
  { titulo: 'Tabela Periódica - Brasil Escola', categoria: 'Química', url: 'https://brasilescola.uol.com.br/quimica/tabela-periodica.htm', descricao: 'Elementos, grupos, períodos e propriedades periódicas' },
  { titulo: 'Química Orgânica - Brasil Escola', categoria: 'Química', url: 'https://brasilescola.uol.com.br/quimica/quimica-organica.htm', descricao: 'Hidrocarbonetos, funções orgânicas e reações' },
  { titulo: 'Biologia Celular - Brasil Escola', categoria: 'Biologia', url: 'https://brasilescola.uol.com.br/biologia/celula.htm', descricao: 'Estrutura celular, organelas e divisão celular' },
  { titulo: 'Genética - Khan Academy', categoria: 'Biologia', url: 'https://pt.khanacademy.org/science/ap-biology/heredity', descricao: 'Leis de Mendel, herança genética e mutações' },
  { titulo: 'Geopolítica Mundial - Brasil Escola', categoria: 'Geografia', url: 'https://brasilescola.uol.com.br/geografia/geopolitica.htm', descricao: 'Blocos econômicos, conflitos e relações internacionais' },
  { titulo: 'Biomas Brasileiros - Toda Matéria', categoria: 'Geografia', url: 'https://www.todamateria.com.br/biomas-brasileiros/', descricao: 'Amazônia, Cerrado, Caatinga, Mata Atlântica e Pantanal' },
  { titulo: 'Gramática Inglesa - British Council', categoria: 'Inglês', url: 'https://learnenglish.britishcouncil.org/grammar', descricao: 'Gramática completa com exercícios interativos' },
  { titulo: 'Inglês para Iniciantes - Duolingo', categoria: 'Inglês', url: 'https://www.duolingo.com/course/en/pt/Learn-English', descricao: 'Curso gratuito de inglês do básico ao avançado' },
  { titulo: 'Filosofia Grega - Brasil Escola', categoria: 'Filosofia', url: 'https://brasilescola.uol.com.br/filosofia/filosofia-grega.htm', descricao: 'Sócrates, Platão, Aristóteles e os pré-socráticos' },
  { titulo: 'Desigualdade Social - Stoodi', categoria: 'Sociologia', url: 'https://www.stoodi.com.br/blog/sociologia/desigualdade-social/', descricao: 'Causas, consequências e indicadores de desigualdade' }
];
